/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "yassAjoutRegister.h"
#include "yassVerifLogin.h"
#include "fonctions.h"

int
main (int argc, char *argv[])
{
  //GtkWidget *yasmine_register_window;
GtkWidget *yasmine_home_window;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 // yasmine_register_window = create_yasmine_register_window ();

yasmine_home_window = create_yasmine_home_window();
GtkTreeView* yasmine_treeview = GTK_TREE_VIEW (lookup_widget(yasmine_home_window,"yasmine_treeview" ) );
afficher_don(yasmine_treeview);
gtk_widget_show (yasmine_home_window);

  gtk_main ();
  return 0;
}

