/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_yasmine_register_window (void);
GtkWidget* create_yasmine_login_window (void);
GtkWidget* create_yasmine_welcome_window (void);
GtkWidget* create_yasmine_home_window (void);
GtkWidget* create_yasmine_ajout_window (void);
GtkWidget* create_yasmine_ajout_confirm_window (void);
GtkWidget* create_yasmine_update_window (void);
GtkWidget* create_yasmine_delete_window (void);
GtkWidget* create_yasmine_delete_confirm_window (void);
GtkWidget* create_yasmine_update_confirm_window (void);
